services:
    app.admin.event:
        class: BlogBundle\Admin\EventAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Evenements", label: "Evenements" }
        arguments:
            - ~
            - BlogBundle\Entity\Event
            - ~
        calls:
            - [ setTranslationDomain, [BlogBundle]]
    app.admin.team:
        class: BlogBundle\Admin\TeamAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Evenements", label: "Equipes" }
        arguments:
            - ~
            - BlogBundle\Entity\Team
            - ~
        calls:
            - [ setTranslationDomain, [BlogBundle]]
    # app.admin.image:
    #     class: BlogBundle\Admin\ImageAdmin
    #     tags:
    #         - { name: sonata.admin, manager_type: orm, group: "Media", label: "Category" }
    #     arguments:
    #         - ~
    #         - BlogBundle\Entity\Image
    #         - ~
    #     calls:
    #         - [ setTranslationDomain, [BlogBundle]]

