<?php
namespace BlogBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class EventRepository extends EntityRepository
{
	/**
     * Gets past events
     * @param integer $max
     * @return array
     */
    public function getPastEvents($max = 15)
    {
        $today = new \DateTime();
        return $this->_em->createQuery('SELECT e from BlogBundle:Event e WHERE e.time < :time ORDER BY e.time DESC')
                    ->setMaxResults($max)
                    ->setParameter('time', $today->format('Y-m-d 00:00:00'))
                    ->getResult();
    }
    /**
     * Gets immediate next event
     * @return mixed
     */
    public function getNextEvent()
    {
        $today = new \DateTime();
        return $this->_em->createQuery('SELECT e from BlogBundle:Event e WHERE e.time > :time ORDER BY e.time ASC')
                    ->setMaxResults(1)
                    ->setParameter('time',$today->format('Y-m-d 00:00:00'))
                    ->getOneOrNullResult();
    }
    /**
     * Gets future event excluding immediate next one
     * @param integer $max
     * @return array
     */
    public function getFutureEvents($max = 15)
    {
        $today = new \DateTime();
        return $this->_em->createQuery('SELECT e from BlogBundle:Event e WHERE e.time > :time ORDER BY e.time ASC')
                    ->setFirstResult(1)
                    ->setMaxResults($max)
                    ->setParameter('time', $today->format('Y-m-d 00:00:00'))
                    ->getResult();
    }
}