imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: sonata_admin.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [EDBlogBundle , BlogBundle , AppBundle, JqueryBundle, HTML5VertiTemplateBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        uglifyjs2:
            bin: /usr/local/bin/uglifyjs
        uglifycss:
            bin: /usr/local/bin/uglifycss
        optipng:
            bin: /usr/bin/optipng
        jpegoptim:
            bin: /usr/bin/jpegoptim
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            translatable:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Translatable\Entity
                # make sure vendor library location is correct
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class:     BlogBundle\Entity\User


sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)
        sonata.block.service.text: 
        sonata.block.service.rss:

        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]

ivory_ck_editor:
    configs:
        default:
            toolbar:                "default"
            filebrowserImageBrowseRoute:      elfinder
            filebrowserImageBrowseParameters:
              mode: image
        extended:
            toolbar:                "extended"
            filebrowserImageBrowseRoute:      elfinder
            filebrowserImageBrowseParameters:
              mode: image
        news:
            toolbar:                "default"
            filebrowserImageBrowseRoute:      elfinder
            filebrowserImageBrowseParameters:
              mode: image
    toolbars:
        configs:
            default:  [ "@paragraph", "@list", "@links", "@tools", [ "Source" ] , "/", [ "Image", "Smiley" ], "@basicstyles", "@styles", "@colors"  ]
            extended: [ "@paragraph", "@list", "@links", "@tools", [ "Source" ] , "/", "@insert", "@basicstyles", "@styles", "@colors"  ]
        items:
            document:     [ 'Source','-','Save','NewPage','DocProps','Preview','Print','-','Templates' ]
            clipboard:    [ 'Cut','Copy','Paste','PasteText','PasteFromWord','-','Undo','Redo' ]
            editing:      [ 'Find','Replace','-','SelectAll','-','SpellChecker', 'Scayt' ]
            forms:        [ 'Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton', 'HiddenField' ]
            basicstyles:  [ 'Bold','Italic','Underline','Strike','Subscript','Superscript','-','RemoveFormat' ]
            paragraph:    [ 'JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock','-','BidiLtr','BidiRtl','-','Blockquote','CreateDiv' ]
            list:         [ 'NumberedList','BulletedList','-','Outdent','Indent' ]
            links:        [ 'Link','Unlink','Anchor' ]
            insert:       [ 'Image','Flash','Table','HorizontalRule','Smiley','SpecialChar','PageBreak','Iframe' ]
            styles:       [ 'Styles','Format','Font','FontSize' ]
            colors:       [ 'TextColor','BGColor' ]
            tools:        [ 'Maximize', 'ShowBlocks','-','About' ]


fm_elfinder:
    instances:
        default:
            locale: %locale% # defaults to current request locale
            editor: ckeditor # other options are tinymce, tinymce4, form, custom and simple
            fullscreen: true # defaults true, applies to simple and ckeditor editors
            theme: smoothness # jquery theme
            include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            connector:
                debug: false # defaults to false
                roots:       # at least one root must be defined
                    uploads:
                        show_hidden: false # defaults to false
                        driver: LocalFileSystem
                        path: uploads
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 2M


sonata_media:
    # if you don't use default namespace configuration
    #class:
    #    media: MyVendor\MediaBundle\Entity\Media
    #    gallery: MyVendor\MediaBundle\Entity\Gallery
    #    gallery_has_media: MyVendor\MediaBundle\Entity\GalleryHasMedia
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr it is mandatory to choose one here
    default_context: default # you need to set a context
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 250 , height: 300 , quality: 140}
    cdn:
        server:
            path: /web/uploads/media # http://media.sonata-project.org/

    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     false

liip_theme:
    themes: ['web', 'tablet', 'phone']
    active_theme: 'web'

html5_cache: ~

html5_verti_template: ~

jquery:
    local: '@AppBundle/Resources/public/js/jquery-1.11.3.min.js'

ed_blog:
    entities:
        user_model_class: BlogBundle\Entity\User
        article_class: BlogBundle\Entity\Article
        article_meta_class: BlogBundle\Entity\ArticleMeta
        blog_term_class: BlogBundle\Entity\Term
        blog_taxonomy_class: BlogBundle\Entity\Taxonomy
        blog_taxonomy_relation_class: BlogBundle\Entity\TaxonomyRelation
        blog_comment_class: BlogBundle\Entity\Comment
        blog_settings_class: BlogBundle\Entity\Settings

liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        my_thumb:
            quality: 75
            filters:
                thumbnail: { size: [120, 90], mode: outbound }